blank_issues_enabled: true
contact_links:
  - name: ğŸ™ Questions & Answers
    url: https://github.com/Xiaokang2022/maliang/discussions/new?category=q-a
    about: Please ask and answer questions here.